% Generated by caw_codegen:caw_generate/3 for the double_all spec.
% This file demonstrates the Stage 4 output for the canonical double_all example.
% (Stage 4 is not yet implemented; this is a hand-authored illustration.)

double_all([], []).
double_all([X|Xs], [Y|Ys]) :-
    Y is X * 2,
    double_all(Xs, Ys).
