% Generated by testgen:spec_to_tests/2 for the double_all spec.
% This file demonstrates the Stage 3 output for the canonical double_all example.

:- begin_tests(double_all).
test(example_1) :-
    double_all([1,2,3], R),
    assertion(R == [2,4,6]).
test(empty) :-
    double_all([], R),
    assertion(R == []).
test(single_item, [todo(single_item_expected_output_not_derived)]) :-
    double_all([single_item_placeholder], _).
test(duplicate_inputs) :-
    double_all([1,1], _).
test(mixed_type_rejection, [fail]) :-
    double_all([1,bad_atom,3], _).
test(variables_in_input, [todo(variables_in_input_behaviour_unspecified)]) :-
    double_all([1,_,3], _).
test(deterministic, [deterministic]) :-
    double_all([], _).
:- end_tests(double_all).
